set -e

cd ../klee
rm -rf build
mkdir build
cd build

# REMOVE
Z3_INCLUDE_DIRS="TODO:"
Z3_LIBRARIES="TODO:"
KLEE_UCLIBC_PATH="TODO:"
LLVM_CONFIG_BINARY="TODO:"

cmake -Wnounused-variable -DCMAKE_BUILD_TYPE=Debug -DENABLE_CLO_DYNAMIC=ON -DENABLE_CLO_DYNAMIC_DEBUG=ON -DCLO_DYNAMIC_OPTION_SEARCHER=OFF -DENABLE_SOLVER_Z3=ON -DZ3_INCLUDE_DIRS=$Z3_INCLUDE_DIRS -DZ3_LIBRARIES=$Z3_LIBRARIES -DENABLE_POSIX_RUNTIME=ON -DKLEE_UCLIBC_PATH=$KLEE_UCLIBC_PATH -DLLVM_CONFIG_BINARY=$LLVM_CONFIG_BINARY ..
make -j4
echo "KLEE build done."